import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
const root = process.cwd();
const generator = join(root, "src/lib/ada-quote-generation.ts");
const route = join(root, "src/app/api/ada/workspaces/[workspaceId]/generate/route.ts");
test("Ada quote generation uses Opus, grounded context, and creates a revision", () => {
  assert.ok(existsSync(generator)); assert.ok(existsSync(route));
  const source = readFileSync(generator, "utf8"); const routeSource = readFileSync(route, "utf8");
  assert.match(source, /selectAdaModel/);
  assert.match(source, /purpose: "quote"/);
  assert.match(source, /project_pricing_index/);
  assert.match(source, /quote_line_items/);
  assert.match(source, /lineItems/);
  assert.match(source, /internalCost/);
  assert.match(source, /clientPrice/);
  assert.match(source, /pricingBasis/);
  assert.match(source, /expert_estimate/);
  assert.match(source, /single best point estimate/i);
  assert.match(source, /never return zero or pending pricing/i);
  assert.match(source, /Only prices stated directly by a user/i);
  assert.match(source, /never relabel Ada's prior estimate as user input/i);
  assert.match(source, /name: "finalize_ada_quote"/);
  assert.match(source, /tool_choice: \{ type: "tool", name: "finalize_ada_quote" \}/);
  assert.doesNotMatch(source, /text\.match\(\/\\\{\[\\s\\S\]\*\\\}\//, "quote generation must not parse freeform JSON text");
  assert.match(routeSource, /requireAdaWorkspaceAccess\(workspaceId, "edit_draft"\)/);
  assert.match(routeSource, /createAdaQuoteRevision/);
  assert.match(routeSource, /actorEmail: access\.actorEmail/);
});
