import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
const root = process.cwd();
const acceptRoute = join(root, "src/app/api/ada/workspaces/[workspaceId]/revisions/[revisionId]/accept/route.ts");
const previewRoute = join(root, "src/app/api/ada/workspaces/[workspaceId]/revisions/[revisionId]/handoff-preview/route.ts");
const canvas = readFileSync(join(root, "src/components/ada-quote-canvas.tsx"), "utf8");
test("Ada commercially approves one revision and previews handoff only after customer acceptance", () => {
  assert.ok(existsSync(acceptRoute));
  assert.ok(existsSync(previewRoute));
  const approved = readFileSync(acceptRoute, "utf8");
  const preview = readFileSync(previewRoute, "utf8");
  assert.match(approved, /accept_ada_quote_revision/);
  assert.match(approved, /status: "commercial_approved"/);
  assert.match(approved, /commercialApprovedRevisionId/);
  assert.doesNotMatch(approved, /status: "accepted"|acceptedRevisionId/);
  assert.match(preview, /customer_accepted_revision_id/);
  assert.match(preview, /event_type", "customer_accepted"/);
  assert.doesNotMatch(preview, /ada_quote_events/);
  assert.match(preview, /proposedActions/);
  assert.doesNotMatch(preview, /fetch\(/);
  assert.match(canvas, /Commercially approve/);
  assert.match(canvas, /internal approval only/);
  assert.match(canvas, /Preview handoff/);
});
