\pset tuples_only on
\pset format unaligned
\set ON_ERROR_STOP on

SELECT '-- MDP Tracker lab schema bootstrap';
SELECT '-- Source project: yaftybqzlbbvzwwdzlny';
SELECT '-- Schema-only catalog export; no production rows included.';
SELECT 'SET statement_timeout = 0;';
SELECT 'SET lock_timeout = 0;';
SELECT 'SET client_encoding = ''UTF8'';';
SELECT 'SET standard_conforming_strings = on;';
SELECT 'SET check_function_bodies = false;';
SELECT 'SET search_path = public, extensions, pg_catalog;';
SELECT 'CREATE SCHEMA IF NOT EXISTS extensions;';
SELECT 'CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA extensions;';
SELECT 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;';
SELECT 'CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;';
SELECT '';

-- Public enum and domain types.
SELECT format('CREATE TYPE public.%I AS ENUM (%s);',t.typname,
              string_agg(quote_literal(e.enumlabel),', ' ORDER BY e.enumsortorder))
FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
JOIN pg_enum e ON e.enumtypid=t.oid
WHERE n.nspname='public' GROUP BY t.oid,t.typname ORDER BY t.typname;
SELECT format('CREATE DOMAIN public.%I AS %s%s%s;',t.typname,
              format_type(t.typbasetype,t.typtypmod),
              CASE WHEN t.typnotnull THEN ' NOT NULL' ELSE '' END,
              CASE WHEN t.typdefault IS NOT NULL THEN ' DEFAULT '||t.typdefault ELSE '' END)
FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
WHERE n.nspname='public' AND t.typtype='d' ORDER BY t.typname;
SELECT '';

-- Standalone and serial sequences; identity sequences are created by tables.
SELECT format('CREATE SEQUENCE public.%I AS %s INCREMENT BY %s MINVALUE %s MAXVALUE %s START WITH %s CACHE %s%s;',
              c.relname,format_type(s.seqtypid,NULL),s.seqincrement,s.seqmin,s.seqmax,s.seqstart,s.seqcache,
              CASE WHEN s.seqcycle THEN ' CYCLE' ELSE ' NO CYCLE' END)
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_sequence s ON s.seqrelid=c.oid
WHERE n.nspname='public' AND NOT EXISTS (
  SELECT 1 FROM pg_depend d WHERE d.objid=c.oid AND d.deptype='i'
) ORDER BY c.relname;
SELECT '';

-- Base tables. Defaults are added later after functions are available.
SELECT format(E'CREATE %sTABLE public.%I (\n%s\n);',
              CASE WHEN c.relpersistence='u' THEN 'UNLOGGED ' ELSE '' END,
              c.relname,
              string_agg(
                '  '||quote_ident(a.attname)||' '||format_type(a.atttypid,a.atttypmod)||
                CASE WHEN coll.oid IS NOT NULL AND coll.oid<>typ.typcollation THEN ' COLLATE '||quote_ident(coll_ns.nspname)||'.'||quote_ident(coll.collname) ELSE '' END||
                CASE a.attidentity WHEN 'a' THEN ' GENERATED ALWAYS AS IDENTITY' WHEN 'd' THEN ' GENERATED BY DEFAULT AS IDENTITY' ELSE '' END||
                CASE WHEN a.attgenerated<>'' THEN ' GENERATED ALWAYS AS ('||pg_get_expr(ad.adbin,ad.adrelid)||') STORED' ELSE '' END||
                CASE WHEN a.attnotnull THEN ' NOT NULL' ELSE '' END,
                E',\n' ORDER BY a.attnum),
              CASE WHEN c.relkind='p' THEN ' PARTITION BY '||pg_get_partkeydef(c.oid) ELSE '' END)
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped
JOIN pg_type typ ON typ.oid=a.atttypid
LEFT JOIN pg_attrdef ad ON ad.adrelid=a.attrelid AND ad.adnum=a.attnum
LEFT JOIN pg_collation coll ON coll.oid=a.attcollation
LEFT JOIN pg_namespace coll_ns ON coll_ns.oid=coll.collnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p')
GROUP BY c.oid,c.relname,c.relpersistence,c.relkind ORDER BY c.relname;
SELECT '';

-- Public functions and procedures. Extension-owned routines are excluded.
SELECT pg_get_functiondef(p.oid)||';'
FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname='public' AND p.prokind IN ('f','p')
  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=p.oid AND d.deptype='e')
ORDER BY p.oid::regprocedure::text;
SELECT '';

-- Deferred column defaults.
SELECT format('ALTER TABLE ONLY public.%I ALTER COLUMN %I SET DEFAULT %s;',
              c.relname,a.attname,pg_get_expr(ad.adbin,ad.adrelid))
FROM pg_attrdef ad JOIN pg_attribute a ON a.attrelid=ad.adrelid AND a.attnum=ad.adnum
JOIN pg_class c ON c.oid=ad.adrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p') AND a.attidentity='' AND a.attgenerated=''
ORDER BY c.relname,a.attnum;

-- Serial sequence ownership.
SELECT format('ALTER SEQUENCE public.%I OWNED BY public.%I.%I;',seq.relname,tbl.relname,a.attname)
FROM pg_depend d JOIN pg_class seq ON seq.oid=d.objid AND seq.relkind='S'
JOIN pg_class tbl ON tbl.oid=d.refobjid JOIN pg_namespace n ON n.oid=tbl.relnamespace
JOIN pg_attribute a ON a.attrelid=tbl.oid AND a.attnum=d.refobjsubid
WHERE n.nspname='public' AND d.deptype='a' ORDER BY seq.relname;
SELECT '';

-- Constraints, including foreign keys to managed auth/storage schemas.
SELECT format('ALTER TABLE ONLY public.%I ADD CONSTRAINT %I %s;',c.relname,con.conname,pg_get_constraintdef(con.oid,true))
FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND con.contype IN ('p','u','c','x','f')
ORDER BY CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'x' THEN 4 WHEN 'f' THEN 5 ELSE 6 END,c.relname,con.conname;
SELECT '';

-- Non-constraint indexes.
SELECT pg_get_indexdef(i.indexrelid)||';'
FROM pg_index i JOIN pg_class c ON c.oid=i.indrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid=i.indexrelid)
ORDER BY c.relname,i.indexrelid::regclass::text;
SELECT '';

-- Views contain definitions only; no materialized-view rows are copied.
SELECT format(E'CREATE VIEW public.%I%s AS\n%s;',c.relname,
              CASE WHEN c.reloptions IS NOT NULL THEN ' WITH ('||array_to_string(c.reloptions,', ')||')' ELSE '' END,
              rtrim(pg_get_viewdef(c.oid,true),';'))
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind='v'
ORDER BY (
  SELECT count(*) FROM pg_rewrite rw JOIN pg_depend d ON d.classid='pg_rewrite'::regclass AND d.objid=rw.oid
  JOIN pg_class dependency ON dependency.oid=d.refobjid JOIN pg_namespace dependency_ns ON dependency_ns.oid=dependency.relnamespace
  WHERE rw.ev_class=c.oid AND dependency_ns.nspname='public' AND dependency.relkind IN ('v','m') AND dependency.oid<>c.oid
),c.relname;
SELECT format(E'CREATE MATERIALIZED VIEW public.%I%s AS\n%s\nWITH NO DATA;',c.relname,
              CASE WHEN c.reloptions IS NOT NULL THEN ' WITH ('||array_to_string(c.reloptions,', ')||')' ELSE '' END,
              rtrim(pg_get_viewdef(c.oid,true),';'))
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind='m' ORDER BY c.relname;
SELECT '';

-- Row-level security and policies.
SELECT format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;',c.relname)
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relrowsecurity ORDER BY c.relname;
SELECT format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY;',c.relname)
FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relforcerowsecurity ORDER BY c.relname;
SELECT format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',p.polname,c.relname,
              CASE WHEN p.polpermissive THEN 'PERMISSIVE' ELSE 'RESTRICTIVE' END,
              CASE p.polcmd WHEN 'r' THEN 'SELECT' WHEN 'a' THEN 'INSERT' WHEN 'w' THEN 'UPDATE' WHEN 'd' THEN 'DELETE' ELSE 'ALL' END,
              (SELECT string_agg(CASE WHEN role_oid=0 THEN 'PUBLIC' ELSE quote_ident(r.rolname) END,', ' ORDER BY role_oid)
               FROM unnest(p.polroles) role_oid LEFT JOIN pg_roles r ON r.oid=role_oid),
              CASE WHEN p.polqual IS NOT NULL THEN ' USING ('||pg_get_expr(p.polqual,p.polrelid)||')' ELSE '' END,
              CASE WHEN p.polwithcheck IS NOT NULL THEN ' WITH CHECK ('||pg_get_expr(p.polwithcheck,p.polrelid)||')' ELSE '' END)
FROM pg_policy p JOIN pg_class c ON c.oid=p.polrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' ORDER BY c.relname,p.polname;
SELECT '';

-- Application triggers.
SELECT pg_get_triggerdef(t.oid,true)||';'
FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace
WHERE n.nspname='public' AND NOT t.tgisinternal ORDER BY c.relname,t.tgname;
SELECT '';

-- Explicit object grants only; default managed grants remain environment-owned.
SELECT format('REVOKE ALL ON FUNCTION %s FROM PUBLIC;',p.oid::regprocedure::text)
FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
WHERE n.nspname='public' AND p.prokind IN ('f','p')
  AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=p.oid AND d.deptype='e')
ORDER BY p.oid::regprocedure::text;

WITH grants AS (
 SELECT c.oid,c.relkind,c.relname,coalesce(r.rolname,'PUBLIC') grantee,a.privilege_type,a.is_grantable
 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
 CROSS JOIN LATERAL aclexplode(c.relacl) a LEFT JOIN pg_roles r ON r.oid=a.grantee
 WHERE n.nspname='public' AND c.relacl IS NOT NULL
)
SELECT format('GRANT %s ON %s public.%I TO %s%s;',
              string_agg(privilege_type,', ' ORDER BY privilege_type),
              CASE WHEN relkind='S' THEN 'SEQUENCE' ELSE 'TABLE' END,relname,
              CASE WHEN grantee='PUBLIC' THEN 'PUBLIC' ELSE quote_ident(grantee) END,
              CASE WHEN is_grantable THEN ' WITH GRANT OPTION' ELSE '' END)
FROM grants GROUP BY oid,relkind,relname,grantee,is_grantable ORDER BY relname,grantee,is_grantable;

WITH grants AS (
 SELECT p.oid,p.oid::regprocedure::text identity,coalesce(r.rolname,'PUBLIC') grantee,a.privilege_type,a.is_grantable
 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
 CROSS JOIN LATERAL aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a LEFT JOIN pg_roles r ON r.oid=a.grantee
 WHERE n.nspname='public' AND p.prokind IN ('f','p')
   AND NOT EXISTS (SELECT 1 FROM pg_depend d WHERE d.objid=p.oid AND d.deptype='e')
)
SELECT format('GRANT %s ON FUNCTION %s TO %s%s;',
              string_agg(privilege_type,', ' ORDER BY privilege_type),identity,
              CASE WHEN grantee='PUBLIC' THEN 'PUBLIC' ELSE quote_ident(grantee) END,
              CASE WHEN is_grantable THEN ' WITH GRANT OPTION' ELSE '' END)
FROM grants GROUP BY oid,identity,grantee,is_grantable ORDER BY identity,grantee,is_grantable;
SELECT '';
SELECT '-- End schema bootstrap.';
