"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { PageShell } from "@/components/ui/page-shell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/constants";

type Entry = { type: string; status: string; sku: string | null; quantity: number; description: string; line_total: number; hours: number; labor: number; materials: number };
type Row = { id: string; name: string; current_hours: number; current_materials: number; proposed_hours: number; proposed_labor: number; proposed_materials: number; eligible: boolean; entries: Entry[] };
type Preview = { summary: { active: number; eligible: number; review: number }; rows: Row[] };

export default function FormulaRebaselinePreviewPage() {
  const router = useRouter(); const [preview, setPreview] = useState<Preview | null>(null); const [loading, setLoading] = useState(true); const [expanded, setExpanded] = useState<string | null>(null);
  async function load() { setLoading(true); const response = await fetch("/api/admin/formula-rebaseline-preview"); const result = await response.json(); if (response.ok) setPreview(result); setLoading(false); }
  useEffect(() => { (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session?.user?.email) return router.replace("/login"); const { data } = await supabase.from("user_roles").select("role").eq("email", session.user.email).single(); if (data?.role !== "admin") return router.replace("/"); void load(); })(); }, []);
  const rows = preview?.rows ?? []; const eligible = rows.filter((row) => row.eligible); const review = rows.filter((row) => !row.eligible && row.entries.length > 0);
  function table(items: Row[], title: string, empty: string) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Project</th><th className="text-right">Current hrs</th><th className="text-right">Proposed hrs</th><th className="text-right">Current materials</th><th className="text-right">Proposed materials</th><th className="p-3">Status</th></tr></thead><tbody>{items.length === 0 ? <tr><td className="p-5 text-muted-foreground" colSpan={6}>{empty}</td></tr> : items.map((row) => <><tr key={row.id} className="border-b cursor-pointer hover:bg-muted/50" onClick={() => setExpanded(expanded === row.id ? null : row.id)}><td className="p-3 font-medium">{row.id} · {row.name}</td><td className="text-right">{row.current_hours}</td><td className="text-right font-medium">{row.proposed_hours}</td><td className="text-right">{formatCurrency(row.current_materials)}</td><td className="text-right">{formatCurrency(row.proposed_materials)}</td><td className="p-3">{row.eligible ? "Ready for review" : row.entries.map((entry) => entry.status).filter((v, i, a) => a.indexOf(v) === i).join(", ")}</td></tr>{expanded === row.id && <tr key={`${row.id}-details`} className="bg-muted/30"><td colSpan={6} className="p-3"><table className="w-full text-xs"><thead><tr className="text-left text-muted-foreground"><th>Formula</th><th>SKU</th><th>Description</th><th className="text-right">Qty</th><th className="text-right">Hours</th><th className="text-right">Labor</th><th className="text-right">Materials</th><th>Status</th></tr></thead><tbody>{row.entries.map((entry, index) => <tr key={index} className="border-t"><td className="py-2">{entry.type}</td><td>{entry.sku ?? "—"}</td><td className="max-w-80 truncate">{entry.description}</td><td className="text-right">{entry.quantity}</td><td className="text-right">{entry.hours.toFixed(1)}</td><td className="text-right">{formatCurrency(entry.labor)}</td><td className="text-right">{formatCurrency(entry.materials)}</td><td>{entry.status}</td></tr>)}</tbody></table></td></tr>}</>)}</tbody></table></div></CardContent></Card>; }
  return <PageShell><div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Formula Rebaseline Review</h1><p className="mt-1 text-sm text-muted-foreground">Preview only. No project budget changes are made here.</p></div><Button variant="outline" onClick={load} disabled={loading}>{loading ? "Loading…" : "Refresh"}</Button></div><div className="grid gap-4 sm:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm">Active projects</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{preview?.summary.active ?? "—"}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Eligible formula previews</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{preview?.summary.eligible ?? "—"}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Review required</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{preview?.summary.review ?? "—"}</CardContent></Card></div>{table(eligible, "Eligible projects", "No active projects are ready for formula review yet.")}{table(review, "Review required", "No formula-input exceptions found.")}</PageShell>;
}