'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {adaFetch} from '@/lib/ada-client';
import {parseQuoteV27} from '@/lib/quote-v27-validation';
import {loadSavedQuotes,invalidateQuoteLibrary} from '@/lib/quote-library-client';
import {createVisibleRefresh} from '@/lib/visible-refresh';
import {FORECAST_STATUSES} from '@/lib/quote-schedule';
import {capacityLoad,capacityProject,dateString,dayNumber,emptyCapacity,emptyOverride,monday,parseCapacity,rosterCapacity,SHOP_TRADES,SUPPORT_TRADES,type CapacityDocument,type CapacityOverride,type CapacityQuote} from '@/lib/capacity';
import styles from './capacity-tracker.module.css';
type SavedQuote=CapacityQuote&{version:number;canEdit:boolean};
const number=(value:number)=>value.toLocaleString('en-US',{maximumFractionDigits:1});
const money=(value:number)=>value.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
function Entry({label,value,onChange,nullable=false}:{label:string;value:number|null;onChange:(value:number|null)=>void;nullable?:boolean}){return <input aria-label={label} type="number" min="0" step="any" key={value??'auto'} defaultValue={value??''} placeholder={nullable?'Quoted':''} onBlur={event=>{const next=event.target.value===''&&nullable?null:Number(event.target.value);if(next!==value)onChange(next);}} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}}/>;}
export function CapacityTracker(){
 const [tab,setTab]=useState('Projects'),[quotes,setQuotes]=useState<SavedQuote[]>([]),[document,setDocument]=useState<CapacityDocument>(emptyCapacity),[version,setVersion]=useState(0),[canEdit,setCanEdit]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[settingsError,setSettingsError]=useState(''),[query,setQuery]=useState(''),[scenario,setScenario]=useState<string[]>([]),[editing,setEditing]=useState<string|null>(null),[plan,setPlan]=useState<CapacityOverride>(emptyOverride);
 const editingRef=useRef(editing);editingRef.current=editing;
 const refreshRef=useRef<ReturnType<typeof createVisibleRefresh<Awaited<ReturnType<typeof loadSavedQuotes>>>>|null>(null);
 const loadQuotes=useCallback(async()=>{await refreshRef.current?.request(true);},[]);
 const loadSettings=useCallback(async()=>{const response=await adaFetch('/api/capacity/settings'),payload=await response.json();setSettingsError(response.ok?'':payload.error||'Settings unavailable.');if(payload.document){setDocument(parseCapacity(payload.document));setVersion(payload.version);setCanEdit(Boolean(payload.canEdit));setDirty(false);}},[]);
 useEffect(()=>{
  let mounted=true;
  const controller=createVisibleRefresh(()=>loadSavedQuotes(),result=>{
   setQuotes(result.quotes);setError('');
   setNotice(result.failures?`${result.failures} quotes could not load. Totals are incomplete — refresh before planning.`:`Loaded ${result.quotes.length} quotes · ${new Date().toLocaleTimeString()}`);
  },error=>{setQuotes([]);setNotice('Totals are unavailable — refresh before planning.');setError(error instanceof Error?error.message:'Quotes could not load.');},()=>window.document.visibilityState==='visible'&&!editingRef.current);
  refreshRef.current=controller;
  const visibility=()=>{if(window.document.visibilityState==='hidden')controller.pause();else void controller.request(true);};
  const saved=()=>{void controller.request(true);};
  const identity=()=>{setQuotes([]);setScenario([]);setEditing(null);setPlan(emptyOverride());editingRef.current=null;controller.pause();void controller.request(true);};
  window.document.addEventListener('visibilitychange',visibility);
  window.addEventListener('quote-workbook-saved',saved);
  window.addEventListener('quote-library-identity-changed',identity);
  const timer=window.setInterval(()=>{void controller.request();},60000);
  void controller.request();
  void loadSettings().catch(error=>{if(mounted)setError(error.message);});
  return()=>{mounted=false;controller.dispose();refreshRef.current=null;window.clearInterval(timer);window.document.removeEventListener('visibilitychange',visibility);window.removeEventListener('quote-workbook-saved',saved);window.removeEventListener('quote-library-identity-changed',identity);};
 },[loadSettings]);
 const previousEditing=useRef(editing);
 useEffect(()=>{if(previousEditing.current&&!editing)void refreshRef.current?.request(true);previousEditing.current=editing;},[editing]);
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(editing)dialog.current?.showModal();},[editing]);
 useEffect(()=>{if(!dirty&&!editing)return;const navigate=(event:MouseEvent)=>{if((event.target as HTMLElement).closest('a[href]')&&!window.confirm('Leave without saving capacity changes?')){event.preventDefault();event.stopPropagation();}};window.document.addEventListener('click',navigate,true);const leave=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',leave);return()=>{window.removeEventListener('beforeunload',leave);window.document.removeEventListener('click',navigate,true);};},[dirty,editing]);
 const projects=useMemo(()=>quotes.map(quote=>capacityProject(quote)),[quotes]);
 const capacities=rosterCapacity(document.settings.roster),tradeNames=Array.from(new Set([...SHOP_TRADES,...document.settings.roster.flatMap(person=>[person.primary,person.secondary]).filter(Boolean),...projects.flatMap(project=>Object.keys(project.trades))]));
 const filtered=projects.filter(project=>project.workspace.toLowerCase().includes(query.toLowerCase()));
 const kind=tab==='Field Load'?'field':'shop',load=capacityLoad(projects,document.settings,kind,scenario),capacity=kind==='shop'?capacities.shop:capacities.field;
 const weeks=Array.from({length:26},(_,i)=>dateString(dayNumber(document.settings.weekStart)+7*i));
 function change(fn:(next:CapacityDocument)=>void){const next=structuredClone(document);fn(next);setDocument(next);setDirty(true);}
 async function saveSettings(){setBusy(true);setError('');try{const parsed=parseCapacity(document);const response=await adaFetch('/api/capacity/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:version,document:parsed})}),payload=await response.json();if(!response.ok)throw new Error(payload.error);setVersion(payload.version);setDirty(false);setNotice('Capacity settings saved.');}catch(error){setError(error instanceof Error?error.message:'Save failed.');}finally{setBusy(false);}}
 async function savePlan(){const quote=quotes.find(quote=>quote.workspaceId===editing);if(!quote?.document)return;setBusy(true);setError('');try{const document=parseQuoteV27({...quote.document,planning:plan});const response=await adaFetch(`/api/quote-workspaces/${quote.workspaceId}/workbook`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:quote.version,document})}),payload=await response.json();if(!response.ok)throw new Error(payload.error);previousEditing.current=null;editingRef.current=null;setEditing(null);invalidateQuoteLibrary();await refreshRef.current?.request();}catch(error){setError(error instanceof Error?error.message:'Plan could not save.');}finally{setBusy(false);}}
 const matrixRow=(label:string,values:number[],cap:number|null,percentage=false)=><tr key={label}><th>{label}</th><td>{cap===null?'—':number(cap)}</td>{values.map((value,i)=><td key={i} className={cap!==null&&value>cap?styles.over:cap!==null&&cap>0&&value/cap>.85?styles.near:undefined}>{percentage?(cap?`${number(value/cap*100)}%`:value?'No capacity':'—'):number(value)}</td>)}</tr>;
 return <main className={styles.page}><header><div><h1>Capacity tracker</h1><p>Saved quote names, dates and hours flow here automatically. Updates refresh every 60 seconds.</p></div><Link href="/quotes">Open quotes</Link><Link href="/quotes/import">Import spreadsheet quotes</Link><button onClick={()=>void loadQuotes().catch(error=>setError(error.message))}>Refresh quotes</button></header>
 <nav role="tablist" aria-label="Capacity sections">{['Roster & Settings','Projects','Shop Load','Field Load'].map(name=><button role="tab" aria-selected={tab===name} key={name} onClick={()=>setTab(name)}>{name}</button>)}</nav>
 <p role="status">{notice}</p>{error&&<p role="alert" className={styles.error}>{error}</p>}{settingsError&&<p role="alert" className={styles.error}>{settingsError}</p>}
 {tab==='Roster & Settings'&&<><div className={styles.toolbar}><label>Week grid starts (Monday)<input aria-label="Week grid starts" type="date" value={document.settings.weekStart} disabled={!canEdit||busy} onChange={event=>{if(event.target.value)change(next=>{next.settings.weekStart=monday(event.target.value);});}}/></label><label>Shop hour distribution<select aria-label="Shop hour distribution" disabled={!canEdit||busy} value={document.settings.allocation} onChange={event=>change(next=>{next.settings.allocation=event.target.value as 'weekdays'|'calendar';})}><option value="weekdays">Weekdays (Mon–Fri)</option><option value="calendar">All calendar days</option></select></label><label>Field hour distribution<select aria-label="Field hour distribution" disabled={!canEdit||busy} value={document.settings.fieldAllocation} onChange={event=>change(next=>{next.settings.fieldAllocation=event.target.value as 'install'|'build';})}><option value="install">Install date + estimated field days</option><option value="build">Build window (spreadsheet method)</option></select></label><button disabled={!canEdit||!dirty||busy} onClick={()=>void saveSettings()}>Save roster & settings</button><button disabled={busy} onClick={()=>{if(!dirty||window.confirm('Discard unsaved roster changes?'))void loadSettings().catch(error=>setError(error.message));}}>Reload settings</button></div>
 <p>Primary trade contributes capacity. Secondary trade is shared flex availability, never extra total hours. I&D, Driver/Pickups and Facility are excluded from blended shop capacity. Hourly rates are reference only and do not change quote pricing.</p>
 <fieldset disabled={!canEdit||busy}><div className={styles.scroll}><table aria-label="Capacity roster"><thead><tr>{['Name','Primary trade','Secondary trade (flex)','Hours / week','Hourly rate $','Active','Notes',''].map((label,i)=><th key={i}>{label}</th>)}</tr></thead><tbody>{document.settings.roster.map((person,index)=><tr key={person.id}>{(['name','primary','secondary'] as const).map(key=><td key={key}><input aria-label={`${key} person ${index+1}`} list={key==='name'?undefined:'capacity-trades'} value={person[key]} onChange={event=>change(next=>{next.settings.roster[index][key]=event.target.value;})}/></td>)}<td><Entry label={`Weekly hours person ${index+1}`} value={person.hours} onChange={value=>change(next=>{next.settings.roster[index].hours=value??0;})}/></td><td><Entry label={`Hourly rate person ${index+1}`} value={person.rate} nullable onChange={value=>change(next=>{next.settings.roster[index].rate=value;})}/></td><td><input aria-label={`Active person ${index+1}`} type="checkbox" checked={person.active} onChange={event=>change(next=>{next.settings.roster[index].active=event.target.checked;})}/></td><td><input aria-label={`Notes person ${index+1}`} value={person.notes} onChange={event=>change(next=>{next.settings.roster[index].notes=event.target.value;})}/></td><td><button onClick={()=>change(next=>{next.settings.roster.splice(index,1);})}>Remove</button></td></tr>)}</tbody></table></div><button onClick={()=>change(next=>{next.settings.roster.push({id:crypto.randomUUID(),name:'New person',primary:'Carpentry',secondary:'',hours:40,rate:null,active:true,notes:''});})}>Add person</button></fieldset>
 <datalist id="capacity-trades">{Array.from(new Set([...tradeNames,...SUPPORT_TRADES])).map(trade=><option key={trade}>{trade}</option>)}</datalist>
 <h2>Weekly capacity</h2><table className={styles.summary}><thead><tr><th>Trade</th><th>Primary hours/week</th><th>Flex hours/week (shared)</th></tr></thead><tbody>{Array.from(new Set([...tradeNames,...SUPPORT_TRADES])).map(trade=><tr key={trade}><th>{trade}</th><td>{number(capacities.primary[trade]??0)}</td><td>{number(capacities.flex[trade]??0)}</td></tr>)}<tr><th>Blended shop</th><td>{number(capacities.shop)}</td><td>Flex is already counted once</td></tr></tbody></table></>}
 {tab==='Projects'&&<><label>Search projects<input aria-label="Search capacity projects" value={query} onChange={event=>setQuery(event.target.value)}/></label><p>All accessible, non-archived quotes appear here. Save a workbook to transfer its dates and hours. Closed won/In production are committed; Lost/Completed leave the load. Quotes without dates or status remain visible as unscheduled.</p><div className={styles.scroll}><table aria-label="Capacity projects"><thead><tr>{['Full-job scenario','Project / quote','Build start','Build finish','Install date','Quote status','Planning override','Probability','Shop hours','Untyped','Field hours','Design hours','Quote total','Flags',...tradeNames].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{filtered.map(project=><tr key={project.workspaceId}><td><input type="checkbox" aria-label={`Full-job scenario ${project.workspace}`} checked={scenario.includes(project.workspaceId)} onChange={event=>setScenario(current=>event.target.checked?[...current,project.workspaceId]:current.filter(id=>id!==project.workspaceId))}/></td><th><Link href={`/quotes/${project.workspaceId}`}>{project.workspace}</Link></th><td>{project.schedule.buildStart||'—'}</td><td>{project.schedule.buildFinish||'—'}</td><td>{project.schedule.installDate||'—'}</td><td>{project.schedule.status||'Unset'}</td><td><button disabled={!quotes.find(q=>q.workspaceId===project.workspaceId)?.canEdit||!project.document} onClick={()=>{setEditing(project.workspaceId);setPlan(structuredClone(project.document?.planning??emptyOverride()));}}>{project.document?.planning?.status||'From quote'} · Edit plan</button></td><td>{number(project.probability*100)}%</td><td>{number(project.shop)}</td><td>{number(project.untyped)}</td><td>{number(project.field)}</td><td>{number(project.demand.design)}</td><td>{money(project.demand.price)}</td><td>{project.flags.join(' · ')||'Ready'}</td>{tradeNames.map(trade=><td key={trade}>{number(project.trades[trade]??0)}</td>)}</tr>)}</tbody></table></div></>}
 {(tab==='Shop Load'||tab==='Field Load')&&<><p>26 weeks from {document.settings.weekStart}. Amber: over 85%; red: over 100%. Partial weeks receive only their overlapping days. {kind==='field'&&document.settings.fieldAllocation==='install'?'Field hours start at install date, across the longest quoted installer duration (calendar days); this is an estimate, not an individual crew assignment.':''}</p>{!capacity&&<p className={styles.error}>No active {kind} roster capacity. Add the roster under Roster & Settings.</p>}{load.unscheduled.length>0&&<p className={styles.error}>Unscheduled {kind} demand: {load.unscheduled.join(', ')}</p>}{projects.some(project=>!project.status)&&<p className={styles.error}>Some quotes have no forecast status and are excluded from weighted load. Set their status in the quote header.</p>}<div className={styles.scroll}><table aria-label={`${tab} weekly grid`} className={styles.matrix}><thead><tr><th>Week of</th><th>Cap/week</th>{weeks.map(week=><th key={week}>{week.slice(5)}</th>)}</tr></thead><tbody>{matrixRow('Committed load',load.committed,capacity)}{matrixRow('Pipeline × probability',load.pipeline,null)}{matrixRow('TOTAL EXPECTED',load.expected,capacity)}{matrixRow('Expected utilization',load.expected,capacity,true)}{matrixRow('Committed utilization',load.committed,capacity,true)}{matrixRow('Selected full-job scenario',load.scenario,capacity)}{kind==='shop'&&Array.from(new Set([...SHOP_TRADES,...Object.keys(load.trades)])).map(trade=>{const hours=load.trades[trade]??Array<number>(26).fill(0);return matrixRow(`${trade} · flex ${number(capacities.flex[trade]??0)}`,hours,trade==='Untyped / other'?null:capacities.primary[trade]??0);})}</tbody></table></div><p>Scenario replaces selected pipeline probabilities with 100%; committed projects are still counted only once. Change selections on Projects.</p></>}
 {editing&&<dialog ref={dialog} aria-label="Edit capacity plan" className={styles.dialog} onCancel={event=>{event.preventDefault();if(!busy)setEditing(null);}}><h2>{quotes.find(quote=>quote.workspaceId===editing)?.workspace} — capacity plan</h2><p>Overrides affect planning only. Clear a field to return to the quoted value.</p><fieldset disabled={busy}><label>Status override<select aria-label="Planning status override" value={plan.status} onChange={event=>setPlan({...plan,status:event.target.value as CapacityOverride['status']})}><option value="">From quote</option>{FORECAST_STATUSES.map(status=><option key={status}>{status}</option>)}</select></label><label>Remaining shop hours<Entry label="Remaining shop hours" value={plan.remainingShop} nullable onChange={value=>setPlan({...plan,remainingShop:value})}/></label><label>Remaining field hours<Entry label="Remaining field hours" value={plan.remainingField} nullable onChange={value=>setPlan({...plan,remainingField:value})}/></label><h3>Remaining hours by trade</h3>{tradeNames.map(trade=><label key={trade}>{trade}<Entry label={`Remaining ${trade}`} value={plan.remainingTrades[trade]??null} nullable onChange={value=>{const trades={...plan.remainingTrades};if(value===null)delete trades[trade];else trades[trade]=value;setPlan({...plan,remainingTrades:trades});}}/></label>)}<label>Notes<textarea aria-label="Planning notes" value={plan.notes} onChange={event=>setPlan({...plan,notes:event.target.value})}/></label><button onClick={()=>void savePlan()}>Save planning changes</button><button onClick={()=>setEditing(null)}>Cancel</button></fieldset></dialog>}
 </main>;
}
