'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {adaFetch} from '@/lib/ada-client';
import {loadQuoteLibrary} from '@/lib/quote-library-client';
import {prequoteSnapshot} from '@/lib/quote-prequote';
import type {QuoteV27} from '@/lib/quote-v27';
export function PrequoteLibrary(){
 const [items,setItems]=useState<{item_id:string;title:string;revision:number}[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[legacy,setLegacy]=useState<{document:QuoteV27;lineId:string;workspace:string}[]>([]);
 async function load(){const response=await adaFetch('/api/prequote-items'),data=await response.json();if(!response.ok)throw new Error(data.error);setItems(data.items);setError('');}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function previous(){setBusy(true);try{const result=await loadQuoteLibrary();setLegacy(result.quotes.flatMap(q=>(q.document.reusableItemIds??[]).map(lineId=>({...q,lineId}))));if(result.failures)setError('Some prior quotes could not load.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function copy(entry:typeof legacy[number]){setBusy(true);try{const response=await adaFetch(`/api/prequote-items/${crypto.randomUUID()}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:0,document:prequoteSnapshot(entry.document,entry.lineId)})}),data=await response.json();if(!response.ok)throw new Error(data.error);setLegacy(rows=>rows.filter(row=>row!==entry));await load();}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <main className="p-6"><h1 className="text-xl font-semibold">Prequote items</h1><p className="my-2 text-sm">Independent reusable items. Review and edit here; changes do not alter quotes that already use an item. Insertion uses current inventory prices.</p><Link href="/quotes" className="underline">Back to quotes</Link><div className="my-4 flex gap-3"><input aria-label="Search reusable library" className="rounded border p-2" placeholder="Search item names…" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh</button><button disabled={busy} onClick={()=>void previous()}>Find earlier saved items</button></div>{error&&<p role="alert">{error}</p>}<table className="w-full text-sm"><thead><tr><th className="text-left">Item name</th><th>Revision</th><th>Review / edit</th></tr></thead><tbody>{items.filter(item=>item.title.toLowerCase().includes(query.toLowerCase())).map(item=><tr key={item.item_id} className="border-b"><td className="py-3">{item.title}</td><td className="text-center">{item.revision}</td><td className="text-center"><Link href={`/prequote-items/${item.item_id}`} className="underline">Open item</Link></td></tr>)}</tbody></table>{!items.length&&!error&&<p>No items yet. Use Save as reusable from a quote.</p>}{legacy.length>0&&<section><h2 className="mt-6 font-semibold">Earlier quote-linked items</h2><p>Copy selected items into this library. Original quote snapshots stay unchanged.</p>{legacy.map((entry,index)=><div key={index} className="my-2">{entry.document.lines.find(line=>line.id===entry.lineId)?.name} · {entry.workspace} <button disabled={busy} onClick={()=>void copy(entry)}>Copy to library</button></div>)}</section>}</main>;
}
