"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { pollPostmortemUntilSettled } from "@/lib/project-postmortem-poll";

type Postmortem = { id: string; status: string; generated_at: string; error_message?: string | null; narrative: { executive_summary?: string; outcome?: string; data_gaps?: string[]; recommendations?: Array<{ recommendation: string }> } };
export function ProjectPostmortemCard({ projectId, status }: { projectId: string; status: string }) {
  const [postmortem, setPostmortem] = useState<Postmortem | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function load() { const response = await fetch(`/api/projects/${projectId}/postmortem`, { cache: "no-store" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? `Could not load post-mortem status (${response.status}).`); setPostmortem(result.postmortem); return result.postmortem as Postmortem | null; }
  useEffect(() => { if (status === "Completed") void load(); }, [projectId, status]);
  async function generate() { setLoading(true); setError(""); try { const response = await fetch(`/api/projects/${projectId}/postmortem/generate`, { method: "POST" }); const raw = await response.text(); let result: { error?: string; id?: string; status?: string } = {}; try { result = JSON.parse(raw); } catch {} if (!response.ok || !result.id) throw new Error(result.error ?? `Generator returned HTTP ${response.status}: ${raw.slice(0, 240) || "no response body"}`); setError("Draft generation is running. Waiting for the saved result…"); const settled = await pollPostmortemUntilSettled<Postmortem>({ load: async () => { const latest = await load(); if (latest && latest.id === result.id) return latest; return { id: result.id!, status: "generating", generated_at: new Date().toISOString(), narrative: {} }; } }); if (settled.status === "draft") { setPostmortem(settled); setError(""); } else if (settled.status === "failed") setError(`Draft generation failed: ${settled.error_message ?? "Unknown error"}`); else setError("Draft generation is still running. Reload this project to check its status."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not generate post-mortem."); } finally { setLoading(false); } }
  if (status !== "Completed") return null;
  const narrative = postmortem?.narrative ?? {};
  return <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Project Post-Mortem</CardTitle><p className="mt-1 text-sm text-muted-foreground">Evidence-grounded closeout review. Drafts never change financial data.</p></div><Button onClick={generate} disabled={loading || postmortem?.status === "generating"}>{loading || postmortem?.status === "generating" ? "Generating…" : postmortem ? "Regenerate draft" : "Generate draft"}</Button></CardHeader><CardContent className="space-y-3">{error && <p className="text-sm text-red-600">{error}</p>}{!postmortem ? <p className="text-sm text-muted-foreground">No post-mortem draft yet.</p> : postmortem.status === "generating" ? <p className="text-sm text-muted-foreground">Draft generation is running. This status is saved and will survive a reload.</p> : postmortem.status === "failed" ? <p className="text-sm text-red-600">Draft generation failed: {postmortem.error_message ?? "Unknown error"}</p> : <><div className="flex items-center gap-2 text-sm"><span className="font-medium">Outcome:</span><span>{narrative.outcome ?? "Not classified"}</span><span className="text-muted-foreground">· Draft generated {new Date(postmortem.generated_at).toLocaleDateString()}</span></div><p className="whitespace-pre-wrap text-sm">{narrative.executive_summary ?? "No executive summary returned."}</p>{narrative.recommendations?.length ? <div><p className="mb-1 text-sm font-medium">Recommendations</p><ul className="list-disc space-y-1 pl-5 text-sm">{narrative.recommendations.slice(0, 5).map((item, index) => <li key={index}>{item.recommendation}</li>)}</ul></div> : null}{narrative.data_gaps?.length ? <div className="rounded bg-amber-50 p-3 text-sm text-amber-900"><span className="font-medium">Data gaps: </span>{narrative.data_gaps.join(" · ")}</div> : null}</>}</CardContent></Card>;
}
