"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import { formatCurrency } from "@/lib/constants";
import { PageShell } from "@/components/ui/page-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { toast } from "sonner";

type Labor = { qbo_entry_id:string; project_id:string; employee_name:string; date:string; reg_hours:number; ot_hours:number; hourly_rate:number };
type Project = { id:string; name:string; job_number:string|null; status:string };
const iso = (d: Date) => d.toISOString().slice(0,10);
export default function LaborReconciliationPage() {
 const router=useRouter(); const today=new Date(); const [start,setStart]=useState(iso(new Date(today.getFullYear(),today.getMonth(),1))); const [end,setEnd]=useState(iso(today)); const [labor,setLabor]=useState<Labor[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [selected,setSelected]=useState(new Set<string>()); const [target,setTarget]=useState(""); const [memo,setMemo]=useState(""); const [loading,setLoading]=useState(true);
 async function load(){setLoading(true); const r=await fetch(`/api/admin/labor-reconciliation?start=${start}&end=${end}`); const j=await r.json(); if(!r.ok){toast.error(j.error);return;} setLabor(j.labor);setProjects(j.projects);setLoading(false);}
 useEffect(()=>{(async()=>{const {data:{session}}=await supabase.auth.getSession();if(!session?.user?.email){router.replace('/login');return;}const {data}=await supabase.from('user_roles').select('role').eq('email',session.user.email).single();if(data?.role!=='admin'){router.replace('/');return;}load();})();},[]);
 const total=useMemo(()=>labor.reduce((s,x)=>s+(x.reg_hours+x.ot_hours)*x.hourly_rate,0),[labor]); const selectedRows=labor.filter(x=>selected.has(x.qbo_entry_id)); const selectedCost=selectedRows.reduce((s,x)=>s+(x.reg_hours+x.ot_hours)*x.hourly_rate,0);
 async function createDraft(){if(!target||!selectedRows.length){toast.error('Select labor entries and a target project.');return;}const sourceIds=[...new Set(selectedRows.map(x=>x.project_id))];const r=await fetch('/api/admin/labor-reconciliation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({periodStart:start,periodEnd:end,targetProjectId:target,sourceProjectId:sourceIds.length===1?sourceIds[0]:null,amount:selectedCost,memo,entryIds:selectedRows.map(x=>x.qbo_entry_id)})});const j=await r.json();if(!r.ok){toast.error(j.error);return;}toast.success('Draft reclass created. QBO posting remains disabled.');setSelected(new Set());setMemo('');}
 return <PageShell><div><h1 className="text-2xl font-bold">Labor Reconciliation</h1><p className="text-sm text-muted-foreground">Review calculated QBO time-activity cost by period. Draft allocations are review-only; QBO posting is disabled pending Venturity’s accounting rules.</p></div><Card><CardContent className="flex flex-wrap gap-3 pt-6"><Input type="date" value={start} onChange={e=>setStart(e.target.value)} className="w-40"/><Input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="w-40"/><Button onClick={load} disabled={loading}>{loading?'Loading…':'Apply period'}</Button></CardContent></Card><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm">Labor entries</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{labor.length}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Calculated cost</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{formatCurrency(total)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Selected for reclass</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{formatCurrency(selectedCost)}</CardContent></Card></div><Card><CardHeader><CardTitle>Draft project reclass</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-3"><Select value={target} onValueChange={(value)=>setTarget(value ?? "")}><SelectTrigger className="w-72"><SelectValue placeholder="Target project"/></SelectTrigger><SelectContent>{projects.filter(p=>p.status==='Active').map(p=><SelectItem key={p.id} value={p.id}>{p.job_number?`${p.job_number} · `:''}{p.name}</SelectItem>)}</SelectContent></Select><Input value={memo} onChange={e=>setMemo(e.target.value)} placeholder="Reason / memo" className="min-w-64 flex-1"/><Button onClick={createDraft}>Create draft</Button></CardContent></Card><Card><CardHeader><CardTitle>Time activity cost</CardTitle></CardHeader><CardContent className="p-0 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3"></th><th>Date</th><th>Employee</th><th>Source project</th><th className="text-right">Hours</th><th className="p-3 text-right">Cost</th></tr></thead><tbody>{labor.map(x=>{const p=projects.find(p=>p.id===x.project_id);const cost=(x.reg_hours+x.ot_hours)*x.hourly_rate;return <tr key={x.qbo_entry_id} className="border-b"><td className="p-3"><input type="checkbox" checked={selected.has(x.qbo_entry_id)} onChange={()=>setSelected(s=>{const n=new Set(s);n.has(x.qbo_entry_id)?n.delete(x.qbo_entry_id):n.add(x.qbo_entry_id);return n;})}/></td><td>{x.date}</td><td>{x.employee_name}</td><td>{p?`${p.job_number??p.id} · ${p.name}`:x.project_id}</td><td className="text-right">{(x.reg_hours+x.ot_hours).toFixed(1)}</td><td className="p-3 text-right">{formatCurrency(cost)}</td></tr>})}</tbody></table></CardContent></Card></PageShell>;
}
